version: '3.8'
name: afs7-0
services:
    afs:
      container_name: afs7-0
      image: fargeo/afs
      build:
        context: ..
        dockerfile: afs/Dockerfile
      command: run_arches
      volumes:
        - ../arches/:/web_root/arches
        - ./:/web_root/afs
        - cantaloupe-data-afs7-0:/web_root/afs/afs/uploadedfiles
      env_file:
        - ./docker/env_file.env
      ports:
        - 8005:8000
      stdin_open: true
      tty: true

    cantaloupe_afs:
      container_name: cantaloupe-afs7-0
      image: uclalibrary/cantaloupe:5.0.3-0
      volumes:
        - cantaloupe-data-afs7-0:/imageroot
      ports:
        - 8184:8182
      env_file:
        - ./docker/env_file.env

networks:
  default:
    external: true
    name: arches7-0-dev

volumes:
    arches-log-afs7-0:
    arches-static-afs7-0:
    cantaloupe-data-afs7-0:
