version: '3.8'
services:
    afs:
      container_name: afs6-2
      image: fargeo/afs
      build:
        context: ..
        dockerfile: afs/Dockerfile
      command: run_arches
      volumes:
        - ../arches/:/web_root/arches
        - ./:/web_root/afs
        - cantaloupe-data-afs6-2:/web_root/afs/afs/uploadedfiles
      env_file:
        - ./docker/env_file.env
      ports:
        - 8001:8000
        - 5678:5678
      stdin_open: true
      tty: true

    cantaloupe_afs:
      container_name: cantaloupe-afs6-2
      image: uclalibrary/cantaloupe:5.0.3-0
      volumes:
        - cantaloupe-data-afs6-2:/imageroot
      ports:
        - 8183:8182
      env_file:
        - ./docker/env_file.env

networks:
  default:
    external: true
    name: arches6-2-dev

volumes:
    arches-log-afs6-2:
    arches-static-afs6-2:
    cantaloupe-data-afs6-2:
