# Generated by Django 3.2.19 on 2023-07-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("models", "10121_workflowhistory"),
    ]

    operations = [
        migrations.CreateModel(
            name='RendererConfig',
            fields=[
                ('configid', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('rendererid', models.UUIDField()),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('config', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'renderer_config',
                'managed': True,
            },
        ),
    ]
