from django.db import migrations


def update_workflow_plugins(apps, schema_editor):
    Plugin = apps.get_model("models", "Plugin")
    plugins = Plugin.objects.all()

    for plugin in plugins:
        if str(plugin.pluginid) == "29512c4e-ed06-4a6b-ae2d-e423817b3f6e":
            plugin.config = {
                "show": False, 
                "is_workflow": True,
                "thumbnailBackgroundColor": "#6ea2d8",
                "thumbnailCircleColor": "#87b9e5",
                "description": "Define regions of interest on an object or sample"
            }
            plugin.helptemplate = "analysis-areas-workflow-help"
        elif str(plugin.pluginid) == "af06e949-5e16-49f0-b23e-e8529e8ce321":
            plugin.config = {
                "show": False,
                "is_workflow": True,
                "thumbnailBackgroundColor": "#7a7ecf",
                "thumbnailCircleColor": "#59699e",
                "description": "Add images to a chemical analysis"
            }
            plugin.helptemplate = "add-chemical-analysis-images-workflow-help"
        elif str(plugin.pluginid) == "c206cfc6-6b4a-481e-a018-8da72aeb7074":
            plugin.config = {
                "show": False, 
                "is_workflow": True,
                "thumbnailBackgroundColor": "#5c61b7",
                "thumbnailCircleColor": "#455486",
                "description": "Upload chemical image files and select an image service"
            }
            plugin.helptemplate = "chemical-analysis-workflow-help"
        elif str(plugin.pluginid) == "a1667717-b7bd-4570-b27a-ec352c767e0e":
            plugin.config = {
                "show": False, 
                "is_workflow": True,
                "thumbnailBackgroundColor": "#9591ef",
                "thumbnailCircleColor": "#b0adf3",
                "description": "A research effort, study, or conservation project"
            }
            plugin.helptemplate = "create-project-workflow-help"
        elif str(plugin.pluginid) == "ef3a374c-f795-4317-aaee-83e1493eabb6":
            plugin.config = {
                "show": False, 
                "is_workflow": True,
                "thumbnailBackgroundColor": "#3e89cd",
                "thumbnailCircleColor": "#6ea7d9",
                "description": "Add objects to an existing project"
            }
            plugin.helptemplate = "project-collection-workflow-help"
        elif str(plugin.pluginid) == "730be1cd-0575-44d7-be68-1316c345a8fb":
            plugin.config = {
                "show": False, 
                "is_workflow": True,
                "thumbnailBackgroundColor": "#3e89cd",
                "thumbnailCircleColor": "#6ea7d9",
                "description": "Project Report Workflow"
            }
            plugin.helptemplate = "project-report-workflow-help"
        elif str(plugin.pluginid) == "1132c953-5d8w-4acb-87c5-39c5b996799e":
            plugin.config = {
                "show": False, 
                "is_workflow": True,
                "thumbnailBackgroundColor": "#3e89cd",
                "thumbnailCircleColor": "#6ea7d9",
                "description": "Review digital data files generated by a lab instrument"
            }
            plugin.helptemplate = "review-dataset-workflow-help"
        elif str(plugin.pluginid) == "1132c953-8af4-4acb-87c5-39c5b996799e":
            plugin.config = {
                "show": False, 
                "is_workflow": True,
                "thumbnailBackgroundColor": "#87bdeb",
                "thumbnailCircleColor": "#a6cdf1",
                "description": "An activity to obtain a portion of an object for analysis"
            }
            plugin.helptemplate = "sample-taking-workflow-help"
        elif str(plugin.pluginid) == "afedd8cd-1ba7-43ec-b3c5-d0fab03525ca":
            plugin.config = {
                "show": False, 
                "is_workflow": True,
                "thumbnailBackgroundColor": "#408acd",
                "thumbnailCircleColor": "#6fa8d9",
                "description": "Digital spectral data files generated by a lab instrument"
            }
            plugin.helptemplate = "upload-dataset-workflow-help"

        plugin.save()

    if "af06e949-5e16-49f0-b23e-e8529e8ce321" not in [str(plugin.pluginid) for plugin in plugins]:
        add_chemical_analysis_images_workflow_plug = Plugin.objects.create(
            pluginid="af06e949-5e16-49f0-b23e-e8529e8ce321",
            name="Add Chemical Analysis Images",
            icon="fa fa-pie-chart",
            component="views/components/plugins/add-chemical-analysis-images-workflow",
            componentname="add-chemical-analysis-images-workflow",
            config={
                "show": False,
                "is_workflow": True,
                "thumbnailBackgroundColor": "#7a7ecf",
                "thumbnailCircleColor": "#59699e",
                "description": "Add images to a chemical analysis"
            },
            slug="add-chemical-analysis-images-workflow",
            sortorder=1,
            helptemplate="add-chemical-analysis-images-workflow-help"
        )
        add_chemical_analysis_images_workflow_plug.save()

    init_workflow_plugin_query = Plugin.objects.filter(pluginid="49507fb0-89c6-47b7-b506-9b2b29a3b8d8")
    if len(init_workflow_plugin_query):
        init_workflow_plugin = init_workflow_plugin_query[0]
        init_workflow_plugin.config = { "show": True }
        init_workflow_plugin.save()



class Migration(migrations.Migration):
    dependencies = [
        ("arches_for_science", "0002_view_plugin_permission"),
    ]

    operations = [
        migrations.RunPython(update_workflow_plugins, migrations.RunPython.noop),
    ]