# Generated by Django 4.2.4 on 2023-11-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arches_for_science', '0002_view_plugin_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManifestXCanvas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manifest', models.TextField()),
                ('canvas', models.TextField(blank=True, null=True)),
                ('digitalresource', models.UUIDField()),
            ],
            options={
                'db_table': 'manifest_x_canvas',
                'managed': True,
            },
        ),
    ]
