# Generated by Django 4.2.4 on 2023-11-20 13:43

from django.db import migrations


def retire_core_primary_descriptor(apps, schema_editor):
    Function = apps.get_model("models", "Function")
    fn = Function.objects.get(pk="60000000-0000-0000-0000-000000000001")
    fn.functiontype = "primarydescriptors_retired"
    fn.name = "(retired) Define Resource Descriptors"
    fn.save()

    # create multi-card function
    Function.objects.create(
        pk="00b2d15a-fda0-4578-b79a-784e4138664b",
        modulename="multicard_resource_descriptor.py",
        classname="MulticardResourceDescriptor",
        functiontype="primarydescriptors",
        name="Multi-card Resource Descriptor",
        description="Configure the name, description, and map popup of a resource",
        defaultconfig=fn.defaultconfig,
        component="views/components/functions/multicard-resource-descriptor",
    )


def restore_core_primary_descriptor(apps, schema_editor):
    Function = apps.get_model("models", "Function")
    fn = Function.objects.get(pk="60000000-0000-0000-0000-000000000001")
    fn.functiontype = "primarydescriptors"
    fn.name = "Define Resource Descriptors"
    fn.save()

    multi_card_fn = Function.objects.get(pk="00b2d15a-fda0-4578-b79a-784e4138664b")
    multi_card_fn.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("arches_for_science", "0003_manifest_x_canvas_x_digitalresource"),
    ]

    operations = [
        migrations.RunPython(
            retire_core_primary_descriptor,
            restore_core_primary_descriptor,
        )
    ]
