# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Add new issues to pipeline project
on:
  issues:
    types:
      - opened
jobs:
  move-assigned-card:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@7ffb872c64bd809d23563a130a0a97d01dfa8f43
        with:
          project: afs-v1.0-iterations
          column: New
          repo-token: ${{ secrets.GITHUB_TOKEN }}